#cloud-config
autoinstall:
  version: 1
  refresh-installer:
    update: true
  apt:
    geoip: true
    preserve_sources_list: false
    primary:
    - arches: [amd64, i386]
      uri: http://archive.ubuntu.com/ubuntu
    - arches: [default]
      uri: http://ports.ubuntu.com/ubuntu-ports
  identity:
    hostname: ubuntu-server
    # echo ubuntu | mkpasswd -m sha512crypt --stdin
    password: $6$hg2y5aO5DRejj9yl$2lW4Jkvi989B5QyeWmB7Qb2ulxwEXQYBshcGDv9ChBrcWYfidQ5uX/n8qSI7pLm3Ho7HeMKEKmRBnotTBlgtq0
    realname: Ubuntu User
    username: ubuntu
  keyboard:
    layout: us
  locale: en_US.UTF-8
  network:
    version: 2
    ethernets:
      id0:
        match:
          name: ens*
        dhcp4: true
        dhcp-identifier: mac
        dhcp4-overrides:
          use-dns: false
        nameservers:
          addresses:
          - 192.168.1.1
  ssh:
    allow-pw: true
    authorized-keys:
    # Study PC / WSL
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDPmH8sRgmWWX5sUA2yrfvZMV3jZPSNEsRLYpQbRFTVwkgFMFibqgzaCkaYmmkx8iwGJCAv+hQpEsdnV90vn2RNBGjeEX6GScr8XYhcapiEx3hcIdjxZskJVllsSwnrgd21QpUPI9Y9CIRYgYGeTwuyhnYl2DvWDCXPOU7HiCoW5mdUuQkl+soio4v8C1aroD5je1Q0usMDFBQ2N+frKGzZseR5zBhWwjRG599Z4JgQWIF1LPc4jPfs24vaMy2kMUW5jDIpQjiE1O+xEfNb7k6qyIVcH6GGEv1AileBHj+IXE8KzyxtoIh88Re2mvVuFIVOsResHf0zP5jJqoOdPmnVmzo+sohD/7T+rhbRCDMEGB6eKTqUR9JWKNj/EEgbsYkzYs8XTZqLhn+4QI6EHa9+G/cautts+NOfSHakSMZ09/bn2xf5UFjdqWKLqS7FQ5qAe20iQibn95YOBgLAKxk5gTfBN0sRXuDovvvuzgE7YYyqeN+rgISWSNN3uIyjISKBCZmImfPp+lnG6ucJj7Uj22+1ark5bYvrOqgzCmhVO+JARCNABPx2I4BGTF0WEDN0hmSeTDsBbhrWLmLl/TqoxSojSTYaAhzXQAYsvcp/mu3MSkIW8S8uKkJWMEXWfQQt3gepK+83nuhh8EMrjXw5RVsHyGwyK9BE+pIhdviC0w== devin.kray@gmail.com"
    # MacBook
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDO1R1i7dP0dY3f3rnlIQjVPsg3p0Xvz/16oZq+cUmE+O3An9qKQNUwWA98EdnMfq09qLpU1OBSafrLjZ8rd4+4KZJNhFgOCX1qq9GDo+o87toYZUvZ6ftdokpgYlYh0sSUxCjbEnaYAr9W2ZYs32fSJAZdoSydUp9gsTlYQJtq4OYKeQd4gd0oJ2F+L3Rv/HwY1U2+ynW4XnsnbfYky9DkQJIgirFwhwsuDot7VMW14mvI1T4IN+rGHfvHsEqsKrVCOUwfsgnNEXR4R5lSE0mNgZiEFnh/F7pA8QGmcKrNv/Fd4cZRdWxtDdrmEVVtbVnlnRrtV0NS9VqJiJm6Rm9QQ9LLemHAGJHT90hUknSB5qw1pxJ/uZ5hCQzOAzfABQ+Jgj4VzT4PpwaGF529v9VSsV6KPPyF0pP8YNKgRaSBxFqFTwIBLH9eBiE0neIHDGBBi3H9pbYtlMHoy9pnepSPPhD4vSiVbFVSFxwKJ9hoVpRKt3gZuhtIMuDVFpgiAHYE9VYSKbfH0FuBLqrNzF0inkn0Luo+wWyCUNO2y+mZZKpm61huCgdWGL4HfSNLKqwxBtG0oKI1GISGzipay9m0u0JrPjeNr0bD0Sg28aDhjEeds6P9Xe/j/QZg6YWW11rUH33GFljHo6Llu9rBfoiM9BJqXDyInkzfYcq91cojmw== devin.kray@gmail.com"
    # iPhone
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXTx2RvLN5ZNNG8OM/0lgA4SRjihnwR57mvHCvaYcSXDsjTVq4NlzTG2kfccTIbNUR+g1t3RUJYeFgWFiY5yxHIupNbO2yDGpkSSVrvrrPGzIMQcMrGIJcF4RSVKaPJ60jDekYgPaV2Se49kfbR9Da6PHU66VnvF/JS3dhGS/wbiw3pVk/uIOaiKmg0Ix8uavhBbYMy9/SsfH5j/eR+rNpXH/HyLWpS39FS+Rvv0ndp0l4JnTTvZyLMptfB2Oqans0NuZn/VdRzyr/km7eOcAFskc4Ffv6F112KOHhYgvve3L9qXrZm0kaoYp9SsHuVbo8VtUlPNgpE4ZevtALgywJBBlCzkXvnrz7vU7iA9h0mePtoW7CWBYuJd533JxDX8Etb9FDl1+rryKYfqjVHO90+FN0xJDniiqYUApTokZkEbzp3Ob2fQyPGjc7uxXMUNhsJoi/GTJfIhdpwKs7fNBI6jpAkuGMo4OZH96LZJ1DtAxvG8pGPOxXt/67YO6gPWwU4A1hVHJ6137dzKpqgUSFIPz0OL18coj8jqmt2UJO48PdkfJ41M+/kqc/oHia+Y2pwXW4nRxBXG3YFnVDbIDZNwavv/AvP7ygp3wZnL61aiKG5mTIB949Lt3z8DCneUIcvFOqyYp/xutHoYL7p4yz/qltIQSjn8H4vOU6l4Mhew== devin.kray@gmail.com"
    # Workbench PC
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMiddUjKM30+14w410mfhEpQ4N9CQ9+AdPK3qwXxMw70 devin.kray@gmail.com"
    install-server: true
  late-commands:
  - shutdown -h now
  # https://curtin.readthedocs.io/en/latest/topics/storage.html
  storage:
    swap:
      size: 0
    config:
    # Root Disk
    - id: root-disk-0
      type: disk
      path: /dev/sda
      wipe: superblock-recursive
      preserve: false
      grub_device: false
      name: ''
      ptable: gpt
    - id: root-partition-0
      type: partition
      device: root-disk-0
      size: 512M
      wipe: superblock
      flag: boot
      number: 1
      preserve: false
      grub_device: true
    - id: root-format-0
      type: format
      fstype: fat32
      volume: root-partition-0
      preserve: false
    - id: root-partition-1
      type: partition
      device: root-disk-0
      size: -1
      wipe: superblock
      flag: ''
      number: 2
      preserve: false
    - id: root-format-1
      type: format
      fstype: ext4
      volume: root-partition-1
      preserve: false
    - id: root-mount-0
      type: mount
      device: root-format-0
      path: /boot/efi
    - id: root-mount-1
      type: mount
      device: root-format-1
      path: /
    # Block device for distributed storage
    - id: block-disk-0
      type: disk
      path: /dev/nvme0n1
      wipe: superblock-recursive
      preserve: false
      grub_device: false
      name: ''
      ptable: gpt
