---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  # dependsOn:
  # - name: sealed-secrets
  #   namespace: kube-system
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: 1.17.1
    env:
      TZ: America/New_York
      ZIGBEE2MQTT_DATA: /data
    config:
      homeassistant: true
      device_options:
        retain: true
      permit_join: true
      mqtt:
        base_topic: zigbee2mqtt
        server: "mqtt://vernemq"
      serial:
        port: /dev/ttyUSB0
      advanced:
        log_output:
        - console
        network_key:
        - 204
        - 61
        - 75
        - 23
        - 44
        - 230
        - 24
        - 203
        - 53
        - 5
        - 248
        - 32
        - 50
        - 84
        - 44
        - 159
      frontend:
        port: 8080
      experimental:
        new_api: true
    securityContext:
      privileged: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - host: zigbee2mqtt.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "zigbee2mqtt.devbu.io"
    persistence:
      data:
        enabled: true
        mountPath: /data
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: "1Gi"
    podAnnotations:
      backup.velero.io/backup-volumes: data
    additionalVolumeMounts:
    - name: usb
      mountPath: /dev/ttyUSB0
    additionalVolumes:
    - name: usb
      hostPath:
        path: /dev/ttyUSB0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - {key: "feature.node.kubernetes.io/custom-zigbee", operator: In, values: ["true"]}
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.8.0
        workingDir: "/data"
        args:
        - --user-data-dir
        - "/data/.vscode"
        - --auth
        - "none"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "internal"
          hosts:
          - host: zigbee2mqtt-config.devbu.io
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - zigbee2mqtt-config.devbu.io
        volumeMounts:
        - name: data
          mountPath: /data
  valuesFrom:
  - kind: Secret
    name: "zigbee2mqtt-helm-values"
