---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-serenity-pv
spec:
  storageClassName: media-serenity
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.40
    path: /volume1/Media
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
