---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-rocinante-pv
spec:
  storageClassName: data-rocinante
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.39
    path: /Data
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
