---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-token
  namespace: cert-manager
spec:
  backendType: secretsManager
  data:
  - key: cert-manager/cloudflare-token
    name: cloudflare-token
