---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-url
  namespace: flux-system
spec:
  backendType: secretsManager
  data:
  - key: flux-system/discord-webhook-url
    name: address
