---

version: '3.7'
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.8.0
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: "America/New_York"
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: "true"
    volumes:
    - nginx-proxy-manager-data:/data
    - letsencrypt-data:/etc/letsencrypt
volumes:
  nginx-proxy-manager-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/share/Data/ContainerStation/nginx-proxy-manager/data'
  letsencrypt-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/share/Data/ContainerStation/nginx-proxy-manager/letsencrypt'
