---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-serenity-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-serenity
  resources:
    requests:
      storage: 1Mi
