---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-rocinante-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-rocinante
  resources:
    requests:
      storage: 1Mi
