---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nodered/node-red
      tag: 1.2.9
    env:
      TZ: "America/New_York"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
      - host: node-red.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "node-red.devbu.io"
    persistence:
      data:
        enabled: true
        mountPath: /data
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: "5Gi"
    podAnnotations:
      backup.velero.io/backup-volumes: data
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
        cpu: 2000m
