---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: actions-runner-system
spec:
  backendType: secretsManager
  data:
  - key: actions-runner-system/github-token
    name: github-token
