---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  releaseName: external-secrets
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://external-secrets.github.io/kubernetes-external-secrets/
      chart: kubernetes-external-secrets
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-external-secrets-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: external-secrets
    fullnameOverride: external-secrets
    env:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      POLLER_INTERVAL_MILLISECONDS: 100000
    envVarsFromSecret:
      AWS_ACCESS_KEY_ID:
        secretKeyRef: aws-credentials
        key: id
      AWS_SECRET_ACCESS_KEY:
        secretKeyRef: aws-credentials
        key: key
    serviceMonitor:
      enabled: true
