---

version: '3'
services:
  postgres:
    image: postgres:12.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: ""
      PGDATA: "/var/lib/postgresql/data"
    ports:
    - "5432:5432"
    volumes:
    - pg-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:4.30
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ""
      PGADMIN_DEFAULT_PASSWORD: ""
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "12080:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    links:
    - postgres:pgsql-server
    depends_on:
    - postgres
  pgbackups:
    image: prodrigestivill/postgres-backup-local:12
    restart: unless-stopped
    environment:
      POSTGRES_HOST: "pgsql-server"
      POSTGRES_DB: "gitea,home-assistant,postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: ""
      POSTGRES_EXTRA_OPTS: "-Z9 --schema=public --blobs"
      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 3
      HEALTHCHECK_PORT: 8080
    volumes:
    - pgbackups-data:/backups
    links:
    - postgres:pgsql-server
    depends_on:
    - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  pg-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/share/Data/ContainerStation/postgresql/data'
  pgadmin-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/share/Data/ContainerStation/pgadmin'
  pgbackups-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/share/Data/ContainerStation/pgbackups'
