---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: oauth2-proxy
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  # dependsOn:
  # - name: sealed-secrets
  #   namespace: kube-system
  values:
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v6.1.1
    replicaCount: 2
    ingress:
      enabled: true
      path: /oauth2
      annotations:
        kubernetes.io/ingress.class: "external"
      hosts:
      - "auth.devbu.io"
      tls:
      - hosts:
        - "auth.devbu.io"
    extraArgs:
      provider: oidc
      oidc-issuer-url: "https://onedr0p.us.auth0.com/"
      skip-provider-button:
      pass-authorization-header:
      email-domain: "*"
      cookie-domain: ".devbu.io"
      whitelist-domain: ".devbu.io"
  valuesFrom:
  - kind: Secret
    name: "oauth2-proxy-helm-values"
