---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  backendType: secretsManager
  data:
  - key: flux-system/github-token
    name: token
