---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 5.5.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  # dependsOn:
  # - name: sealed-secrets
  #   namespace: kube-system
  values:
    controllerType: deployment
    image:
      repository: homeassistant/home-assistant
      tag: 2021.2.1
    env:
      TZ: "America/New_York"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      type: LoadBalancer
      externalIPs:
      - 192.168.69.105
      externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
      hosts:
      - host: hass.devbu.io
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "hass.devbu.io"
    prometheus:
      serviceMonitor:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: "10Gi"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.8.0
        workingDir: "/config"
        args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "internal"
          hosts:
          - host: hass-config.devbu.io
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - hass-config.devbu.io
        volumeMounts:
        - name: config
          mountPath: /config
        - name: deploykey
          mountPath: /root/.ssh/id_rsa
          subPath: id_rsa
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
      limits:
        memory: 3000Mi
  valuesFrom:
  - kind: Secret
    name: "home-assistant-helm-values"
